# Generated by Django 6.0 on 2025-12-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='timezone.now', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='pty', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='9640', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(choices=[('GP', 'Gauteng'), ('WC', 'Western Cape'), ('KZN', 'KwaZulu-Natal'), ('FS', 'Free State'), ('EC', 'Eastern Cape'), ('NW', 'North West'), ('MP', 'Mpumalanga'), ('LP', 'Limpopo'), ('NC', 'Northern Cape')], default='GP', max_length=50),
            preserve_default=False,
        ),
    ]
